#!/bin/bash
#
#	/etc/init.d/PHPDaemon
#
# Starts the at PHPDaemon Daemon
#
# chkconfig: 345 95 5
# description: Runs the demonstration daemon.
# processname: PHPDaemon
 
# Source function library.
. /etc/init.d/functions

# define the APP_PATH
APP_PATH=/PHPDaemon
MODULE=PHPDaemon
LOCK_FILE=/var/lock/subsys/${MODULE}.lock
BIN=$APP_PATH/Daemon.php
PID_FILE=/var/run/${MODULE}.pid
PROCESS_NUM=1

#verify that the executable exists
test -x $BIN || exit 0
 
start() {
	# Check if Daemon is already running
	if [ ! -f $LOCK_FILE ]; then
	    echo -n $"Starting $MODULE: "
	    daemon --pidfile=$PID_FILE $BIN --module=$MODULE --process=$PROCESS_NUM
	    RETVAL=$?
	    [ $RETVAL -eq 0 ] && touch $LOCK_FILE
	    echo
	fi
 
	return $RETVAL
}
 
stop() {
	echo -n $"Stopping $MODULE: "
	killproc -p $PID_FILE
	RETVAL=$?
	if [ $RETVAL -eq 0 ]; then
		rm -f $LOCK_FILE
		rm -f $PID_FILE
	fi
	echo
        return $RETVAL
}
 
restart() {
	stop
	start
}	
 
reload() {
	restart
}	
 
status_at() {
 	status -p $PID_FILE $BIN
}
 
case "$1" in
start)
	start
	;;
stop)
	stop
	;;
reload|restart)
	restart
	;;
condrestart)
        if [ -f $LOCK_FILE ]; then
            restart
        fi
        ;;
status)
	status_at
	;;
*)
 
echo $"Usage: $0 {start|stop|restart|condrestart|status}"
	exit 1
esac
 
exit $?
exit $RETVAL